### PR TITLE
transferred the dummy data to the parent reducer initial state

### PR DESCRIPTION
**Pull request by cn8817**
What I did: 
- transferred the dummy data to the parent reducer initial state

What files were changed:
- src/redux/reducers/ParentReducers

Why were these changed made:
- to use the reducer initial state instead so when we have backend endpoints we can pull data correctly

coauthor @vasqueza91 

!(https://www.loom.com/share/de8c31625e1e4e9fbdf47bdaa3069c48)

### CODE REVIEW

**Review by WillisLi — COMMENTED** [review]
Could you take a look at our seeds in the backend repo? I've updated the dummy data to conform to the new schema.

**Review by WillisLi — COMMENTED** [review]
For the messages array we'll still need that `sent_at` field for dummy data, postgres will autofill that once the api is up, but for now, we'll need to manually input that, otherwise, everything looks good. I'm not sure if you want to take a look our values just and use them instead of lorem ipsum

**Comment by Jie-chelchel** [comment]
> Could you take a look at our seeds in the backend repo? I've updated the dummy data to conform to the new schema.

Hi Willis, I am looking at the seed file, 011_instructor_list.js, 
 { instructor_id: 1, course_id: 3, approved: true, approved_by: 3 },
{ instructor_id: 3, course_id: 3, approved: true, approved_by: 1 },

I saw this two lines, does that mean both instructors with id 1 and 3 are going to teach course with id 3? Thank you.

**Comment by WillisLi** [comment]
> > Could you take a look at our seeds in the backend repo? I've updated the dummy data to conform to the new schema.
> 
> Hi Willis, I am looking at the seed file, 011_instructor_list.js, { instructor_id: 1, course_id: 3, approved: true, approved_by: 3 }, { instructor_id: 3, course_id: 3, approved: true, approved_by: 1 },
> 
> I saw these two lines, does that mean both instructors with id 1 and 3 are going to teach the same course with id 3? Thank you.

Yes, the instructor_list table will contain all the courses teachers are able to teach. The relationship between courses and instructors is many to many so there can be more than one instructor qualified to teach a course. This is not to be confused with the schedules table, which are upcoming courses put up by instructors.

**Review by WillisLi — APPROVED** [review]

**Comment by Jie-chelchel** [comment]
> > > Could you take a look at our seeds in the backend repo? I've updated the dummy data to conform to the new schema.
> > 
> > 
> > Hi Willis, I am looking at the seed file, 011_instructor_list.js, { instructor_id: 1, course_id: 3, approved: true, approved_by: 3 }, { instructor_id: 3, course_id: 3, approved: true, approved_by: 1 },
> > I saw these two lines, does that mean both instructors with id 1 and 3 are going to teach the same course with id 3? Thank you.
> 
> Yes, the instructor_list table will contain all the courses teachers are able to teach. The relationship between courses and instructors is many to many so there can be more than one instructor qualified to teach a course. This is not to be confused with the schedules table, which are upcoming courses put up by instructors.

OK, that is clear now. Thanks.

**Review by ashtilawat23 — APPROVED** [review]

**Pull request merged**
